[FEATURE] Add category option to import command
svenpet90/twitter2news pull request #6
Opened 2023-01-25 15:06 UTC by dskzpt-rh

| Q         | A                                                                                                                        |
|-----------|--------------------------------------------------------------------------------------------------------------------------|
| Bug fix?  |no                                                                                                                   |
| New feature? | yes                                                                     |
| BC break? | no                                                                                                                   |
| License   | MIT                                                                                                                      |
 
This PR implements a category option to the import command to save the imported tweets to one or multiple categories.

2023-01-25 17:23 UTC, svenpet90 requested changes
Thanks for the PR! 
~~Please just rename the new option from "category" to "categories" since its can be multiple/ is an array of category uids :-)~~

~~Also please edit the README file accordingly.~~

Thanks a ton!

2023-01-26 07:35 UTC, svenpet90 approved these changes, later dismissed

2023-01-26 08:41 UTC, dskzpt-rh commented
I also added a warn message if a category is invalid, which will also be written to the logfile.

2023-01-26 08:44 UTC, svenpet90 approved these changes

2023-01-26 08:45 UTC, merged